version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: hero-foundry-postgres
    environment:
      POSTGRES_DB: hero_foundry
      POSTGRES_USER: hero_foundry
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/schema:/docker-entrypoint-initdb.d/schema
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hero_foundry -d hero_foundry"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - hero-foundry-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: hero-foundry-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./database/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - hero-foundry-network
    restart: unless-stopped

  # pgAdmin (Optional - Database Management UI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hero-foundry-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@herofoundry.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./database/pgadmin-servers.json:/pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hero-foundry-network
    restart: unless-stopped
    profiles:
      - tools

  # Redis Commander (Optional - Redis Management UI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: hero-foundry-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
      HTTP_USER: admin
      HTTP_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - hero-foundry-network
    restart: unless-stopped
    profiles:
      - tools

  # MailHog (Optional - Email Testing)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: hero-foundry-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - hero-foundry-network
    restart: unless-stopped
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  hero-foundry-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
